export const FETCH_GITHUB_PROFILE = 'FETCH_GITHUB_PROFILE';
export const FETCH_GITHUB_PROFILE_SUCCESS = 'FETCH_GITHUB_PROFILE_SUCCESS';
export const FETCH_GITHUB_PROFILE_FAILURE = 'FETCH_GITHUB_PROFILE_FAILURE';
export const POST_REPOSITORY_INFORMATION = 'POST_REPOSITORY_INFORMATION';